import type { Calibration } from "../api";
import type {
  GameId,
  TemplateSpec,
  Translator,
  DotsDensity,
  DotsJitter,
  DotsPlayable,
  MazeSize,
  MazeType,
  BattleshipsSize,
  SudokuDifficulty,
  CurveMorphSettings,
  NoodlesSettings,
} from "./types";
import { buildDotsBoxesTemplate } from "./dotsBoxes";
import { buildTicTacToeTemplate } from "./ticTacToe";
import { buildBattleshipsTemplate } from "./battleships";
import { buildConnectFourTemplate } from "./connectFour";
import { buildMetaTicTacToeTemplate } from "./metaTicTacToe";
import { buildBingoTemplate } from "./bingo";
import { buildCityCountryRiverTemplate } from "./cityCountryRiver";
import { buildCurveMorphTemplate } from "./curveMorph";
import { buildNoodlesTemplate } from "./noodles";

export function buildTemplate(
  gameId: GameId,
  cal: Calibration,
  t: Translator,
  seeds: {
    dotsBoxes: { density: DotsDensity; seed: number; jitter: DotsJitter; playable: DotsPlayable };
    battleships: BattleshipsSize;
    maze: number;
    mazeSettings: { size: MazeSize; type: MazeType };
    sudoku: { difficulty: SudokuDifficulty; seed: number };
    bingo: number;
    curveMorph: CurveMorphSettings;
    noodles: NoodlesSettings;
  },
): TemplateSpec {
  if (gameId === "dotsBoxes") return buildDotsBoxesTemplate(cal, t, seeds.dotsBoxes);
  if (gameId === "ticTacToe") return buildTicTacToeTemplate(cal, t);
  if (gameId === "maze") throw new Error("Maze templates are generated by the backend API.");
  if (gameId === "battleships") return buildBattleshipsTemplate(cal, t, seeds.battleships);
  if (gameId === "connectFour") return buildConnectFourTemplate(cal, t);
  if (gameId === "metaTicTacToe") return buildMetaTicTacToeTemplate(cal, t);
  if (gameId === "sudoku") throw new Error("Sudoku templates are generated by the backend API.");
  if (gameId === "bingo") return buildBingoTemplate(cal, seeds.bingo, t);
  if (gameId === "cityCountryRiver") return buildCityCountryRiverTemplate(cal, t);
  if (gameId === "curveMorph") return buildCurveMorphTemplate(cal, t, seeds.curveMorph);
  if (gameId === "noodles") return buildNoodlesTemplate(cal, t, seeds.noodles);
  throw new Error(t("games.notReadyHint"));
}
