"""Persistence for stroke fonts.

Each font is one JSON document at ``data/stroke_fonts/<id>.json``. A small
``stroke-fonts.json`` index holds summaries so listings don't have to read every
full document. The index is rebuilt from disk if it goes missing or stale, so the
documents remain the source of truth.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

from ..calibration import data_dir
from .model import (
    _error,  # shared ServiceError factory
    empty_document,
    new_font_id,
    normalize_document,
    now_iso,
    summarize,
)

# Font ids are generated by us as ``stroke-<hex>``; validating the shape before
# building a path keeps untrusted URL input from escaping the storage dir.
_ID_RE = re.compile(r"^stroke-[a-z0-9]+$")


def stroke_fonts_dir() -> Path:
    path = data_dir() / "stroke_fonts"
    path.mkdir(parents=True, exist_ok=True)
    return path


def _index_path() -> Path:
    return stroke_fonts_dir() / "stroke-fonts.json"


def _doc_path(font_id: str) -> Path:
    if not _ID_RE.match(font_id):
        raise _error("Schrift nicht gefunden", 404)
    return stroke_fonts_dir() / f"{font_id}.json"


def _read_doc(path: Path) -> dict:
    try:
        data = json.loads(path.read_text())
    except Exception as exc:
        raise _error("Stroke-Font konnte nicht gelesen werden", 500) from exc
    if not isinstance(data, dict):
        raise _error("Stroke-Font hat ein ungültiges Format", 500)
    return data


def _write_doc(font_id: str, document: dict) -> None:
    _doc_path(font_id).write_text(json.dumps(document, indent=2, ensure_ascii=False))


def _rebuild_index() -> list[dict]:
    summaries: list[dict] = []
    for path in sorted(stroke_fonts_dir().glob("stroke-*.json")):
        try:
            summaries.append(summarize(_read_doc(path)))
        except Exception:
            # A single unreadable document must not break the whole listing.
            continue
    _write_index(summaries)
    return summaries


def _write_index(summaries: list[dict]) -> None:
    _index_path().write_text(json.dumps(summaries, indent=2, ensure_ascii=False))


def list_summaries() -> list[dict]:
    path = _index_path()
    if not path.exists():
        return _rebuild_index()
    try:
        data = json.loads(path.read_text())
    except Exception:
        return _rebuild_index()
    if not isinstance(data, list):
        return _rebuild_index()
    return [item for item in data if isinstance(item, dict) and item.get("id")]


def _refresh_index(document: dict) -> None:
    summaries = [s for s in list_summaries() if s.get("id") != document["id"]]
    summaries.append(summarize(document))
    summaries.sort(key=lambda s: (str(s.get("label") or ""), str(s.get("id") or "")))
    _write_index(summaries)


def create(label: str) -> dict:
    font_id = new_font_id()
    document = empty_document(label, font_id=font_id)
    _write_doc(font_id, document)
    _refresh_index(document)
    return document


def get(font_id: str) -> dict:
    path = _doc_path(font_id)
    if not path.exists():
        raise _error("Schrift nicht gefunden", 404)
    return _read_doc(path)


def create_from_document(document: dict) -> dict:
    """Persist an already-normalized document under its own id (e.g. import)."""
    _write_doc(document["id"], document)
    _refresh_index(document)
    return document


def save(font_id: str, raw_document: dict) -> dict:
    existing = get(font_id)  # 404s if unknown
    document = normalize_document(
        raw_document, font_id=font_id, created_at=existing.get("createdAt")
    )
    document["updatedAt"] = now_iso()
    _write_doc(font_id, document)
    _refresh_index(document)
    return document


def delete(font_id: str) -> None:
    path = _doc_path(font_id)
    if not path.exists():
        raise _error("Schrift nicht gefunden", 404)
    path.unlink(missing_ok=True)
    summaries = [s for s in list_summaries() if s.get("id") != font_id]
    _write_index(summaries)
